config/routes.rb
Epicurio::Application.routes.draw do

  get "comments/index"
  get "comments/new"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users
  resources :users
  resources :foods
  resources :recipes do
    resources :comments
  end

  get 'tags/:tag', to: 'recipes#index', as: :tag

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessible :author, :summary, :cook_time, :ingredients, :name, :prep_time,
                  :preparation, :servings, :image, :image_name, :remote_image_url, :tag_list

  validates_presence_of :name, :author, :ingredients

  mount_uploader :image, ImageUploader

  acts_as_taggable

  has_many :comments, as: :commentable

  #has_many :ingredients, as: :itemable, dependent: :destroy

  #monetize :total_cents
  #
  #def total_cents
  #  #line_items.sum(&:price)
  #  cart_total = 0
  #  line_items.each do |li|
  #    cart_total += li.price * li.quantity
  #  end
  #  return cart_total
  #end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    if params[:tag]
      #@recipes = Recipe.tagged_with(params[:tag]).order("name ASC")
      @recipes = Recipe.tagged_with(params[:tag])
      @tag_name = params[:tag]
    else
      #@recipes = Recipe.order("name ASC").all
      @recipes = Recipe.all
    end
    @users = User.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @commentable = @recipe
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    authorize! :update, @user, :message => 'Members may only edit recipes which are their own.'
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    authorize! :update, @user, :message => 'Members may only delete recipes which are their own.'
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :html => { multipart: true,
                                 :class => 'form-horizontal' }) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this
        recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.label :servings %>
    <%= f.number_field :servings %>
  </div>
  <div class="control-group">
    <%= f.label :prep_time %>
    <%= f.text_field :prep_time %>
  </div>
  <div class="control-group">
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time %>
  </div>
  <div class="control-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, size: "60x12", class: "span5" %>
  </div>
  <div class="control-group">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients, size: "60x12", class: "span5" %>
  </div>
  <div class="control-group">
    <%= f.label :preparation %>
    <%= f.text_area :preparation, size: "60x12", class: "span5" %>
  </div>
  <div class="control-group">
    <%= f.label "Author/Source:" %>
    <%= f.text_field :author %>
  </div>

  <% if @recipe.image? %>
    <div>
      Current image of the prepared recipe:<br>
      <%= (image_tag @recipe.image_url(:medium), :class => "img-polaroid") %>
      <br><br>
    </div>
  <% end %>

  <div class="control-group">
    <% if @recipe.image? %>
      Upload a new image of the prepared recipe (replacing the current one):
    <% else %>
      Upload an image of the prepared recipe:
    <% end %>
      <br>
      <%= f.label :image_name %>
      <%= f.text_field :image_name %>
      <%= f.file_field :image %>
      <%= f.label :remote_image_url, "or image URL" %>
      <%= f.text_field :remote_image_url %>
  </div>

  <div class="control-group">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', root_path, class: "btn" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<h2><%= @recipe.name %></h2>

<%= render 'form' %>

<%= link_to 'Show Recipe', @recipe, class: "btn" %>
<%= link_to 'Back to Recipe Listing', recipes_path, class: "btn" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div id="recipe-listing" class="span8">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td class="thumb"><%= (link_to (image_tag recipe.image_url(:thumb), :class => "img-polaroid"), recipe) if recipe.image? %></td>
          <td class="overview">
            <div><h3 class="margin-reset"><%= link_to recipe.name, recipe, :class => "recipe-name-link" %></h3></div>
            <div><h6 class="inline">Servings:</h6> <%= recipe.servings %></div>
            <div><h6 class="inline">Summary:</h6>
              <%=raw truncate((recipe.summary), :length => 180, :omission => link_to(" ... more", recipe)) %></div>
            <div><h6 class="inline">Author/Source:</h6> <%= recipe.author %></div>
            <div><h6 class="inline">Tags:</h6> <%= raw recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></div>
          </td>
          <td class="actions">
            <%= link_to 'Show', recipe, :class => 'btn btn-mini' %>
            <% if user_signed_in? %>
              <% if (current_user.has_role? :admin) || (current_user.has_role? :member) %>
                <br><%= link_to 'Edit', edit_recipe_path(recipe), :class => 'btn btn-mini' %>
              <% end %>
              <% if (current_user.has_role? :admin) %>
                <br><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="sidebar" class="span4">
  <h3>Tag Cloud</h3>
  <div id="tag_cloud">
    <% tag_cloud Recipe.tag_counts, %w{xxs xs s m l xl xxl} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
  <% if @tag_name %>
    <div class="filtered-tag-name">
      <h5>Viewing the list of recipes tagged with the tag: "<%= @tag_name %>"</h5>
    </div>
  <% end %>
  <div class="users">
    <h3>Users</h3>
    <p>Click on a user's name to view the list of recipes they've created:</p>
    <ul>
      <% @users.each do |user| %>
        <li>
           <% if user.name == "" %>
            <%= link_to user.email, user_path(user) %>
           <% else %>
            <%= link_to user.name, user_path(user) %>
           <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1>Featured Recipe</h1>
<h2><%= @recipe.name %></h2>

<div id="recipe">
  <div class="row">
    <% if @recipe.image? %>
      <div class="image span3">
        <%= image_tag @recipe.image_url(:large), :class => "img-polaroid" %>
      </div>
    <div class="recipe-content span9">
    <% else %>
    <div class="recipe-content span11">
    <% end %>
      <div class="overview">
        <h5 class="inline">Servings:</h5> <%= @recipe.servings %><br>
        <h5 class="inline">Prep time:</h5> <%= @recipe.prep_time %><br>
        <h5 class="inline">Cook time:</h5> <%= @recipe.cook_time %><br><br>
        <h5 class="inline">Summary:</h5><br>
        <%= simple_format(@recipe.summary) %>
      </div>

      <div class="main-details">
        <div class="ingredients">
          <h5 class="inline">Ingredients:</h5><br>
          <%= simple_format(@recipe.ingredients) %>
        </div>

        <div class="preparation">
          <h5 class="inline">Preparation:</h5><br>
            <%= simple_format(@recipe.preparation) %>
        </div>
      </div>

      <div class="meta-info">
        <h5 class="inline">Author/Source:</h5> <%= @recipe.author %><br>
        <h5 class="inline">Tags:</h5> <%=raw @recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </div>
    </div>
  </div>
</div>

<div class="crud-links">
  <% if user_signed_in? %>
    <% if (current_user.has_role? :admin) || (current_user.has_role? :member) %>
      <%= link_to 'Edit Recipe', edit_recipe_path(@recipe), :class => "btn" %>
    <% end %>
  <% end %>
  <%= link_to 'Back to Recipe Listing', recipes_path, :class => "btn" %>
</div>


<% if user_signed_in? %>
  <% if (current_user.has_role? :member) || ((current_user.has_role? :admin)) %>
    <div id="comments">
      <h3>Comments</h3>
      <div id="disqus_thread"></div>
      <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'epicurio'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>

    <!-- DIY comments, disabled in deference to use of disqus comments -->
    <!--<div id="comments">-->
    <!--<h3>Comments</h3>-->

    <!--<%#= render "comments/comments" %>-->
    <!--<%#= render "comments/form" %>-->
    <!--</div>-->
  <% end %>
<% end %>