config/routes.rb
Epicurio::Application.routes.draw do

  get "comments/index"
  get "comments/new"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users
  resources :users
  resources :foods
  resources :recipes do
    resources :comments
  end

  get 'tags/:tag', to: 'recipes#index', as: :tag

end

app/models/food.rb
class Food < ActiveRecord::Base

  attr_accessible :ndb_no, :shrt_desc, :water, :energ_kcal, :protein,
                  :lipid_tot, :ash, :carbohydrt, :fiber_td, :sugar_tot,
                  :calcium, :iron, :magnesium, :phosphorus, :potassium,
                  :sodium, :zinc, :copper, :manganese, :selenium, :vit_c,
                  :thiamin, :riboflavin, :niacin, :panto_acid,  :vit_b6,
                  :folate_tot, :folic_acid, :food_folate, :folate_dfe,
                  :vit_b12, :vit_a_iu, :vit_a_rae, :retinol, :vit_e,
                  :vit_k, :alpha_carot, :beta_carot, :beta_crypt,
                  :lycopene, :lut_zea, :fa_sat, :fa_mono, :fa_poly,
                  :cholesterl, :gmwt_1, :gmwt_desc1, :gmwt_2, :gmwt_desc2,
                  :refuse_pct, :name, :unit_of_measure

  has_many :ingredients

  validates :ndb_no, presence: true, uniqueness: true
  #validates :price, presence: true, numericality: true

  #monetize :total_cents, :allow_nil => true
  #
  #def total_cents
  #  price.present? ? price : 0
  #end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    #@foods = Food.all
    #@foods = Food.find(:all, :order => "shrt_desc ASC")
    #@foods = Food.where(:id => 1..100)
    @foods = Food.where(:id => 1..100).order("shrt_desc ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Food</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Serving Amt.</th>
    <th>Calories</th>
    <th>Saturated Fat</th>
    <th>Mono-unsaturated Fat</th>
    <th>Poly-unsaturated Fat</th>
    <th>Carbohydrate</th>
    <th>Sugar</th>
    <th>Protein</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @foods.each do |food| %>
    <tr>
      <td width="100px"><%= food.shrt_desc %></td>
      <td><%= food.gmwt_desc1 %></td>
      <td><%= food.energ_kcal %></td>
      <td><%= food.fa_sat %></td>
      <td><%= food.fa_mono %></td>
      <td><%= food.fa_poly %></td>
      <td><%= food.carbohydrt %></td>
      <td><%= food.sugar_tot %></td>
      <td><%= food.protein %></td>
      <td><%= link_to 'Show', food, :class => 'btn btn-mini' %></td>
      <td><%= link_to 'Edit', edit_food_path(food), :class => 'btn btn-mini' %></td>
      <td><%= link_to 'Destroy', food, method: :delete,
                      data: { confirm: 'Are you sure?' },
                      :class => 'btn btn-mini btn-danger' %></td>
    </tr>
  <% end %>
</table>

<!--<br />-->

<%#= link_to 'New Ingredient', new_food_path, :class => 'btn btn-mini
btn-primary' %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>