config/routes.rb
Epicurio::Application.routes.draw do

  get "comments/index"
  get "comments/new"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => 'home#index'

  devise_for :users
  resources :users
  resources :foods
  resources :recipes do
    resources :comments
  end

  get 'tags/:tag', to: 'recipes#index', as: :tag

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Epicurio", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
      <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
        <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <li>
      <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/_navigation_main.html.erb
<%= link_to "Epicurio", root_path, :class => 'brand' %>
<ul class="nav">
    <li><%= link_to "All Recipes", recipes_path %></li>
  <% if user_signed_in? %>
    <% if (current_user.has_role? :member) || ((current_user.has_role? :admin)) %>
      <li>
        <%= link_to "Add New Recipe", new_recipe_path %>
      </li>
    <% end %>
    <% if current_user.has_role? :admin %>
      <li><%= link_to "Food DB", foods_path %></li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_navigation_user.html.erb
<div class="login-status-msg">
  <% if user_signed_in? %>
    You are logged-in as <%= current_user.email %>, and are browsing as
    <% if current_user.has_role? :admin %> an <% else %> a <% end %>
    <%= current_user.roles.sort.first.name.titlecase %> User
  <% else %>
    You are not registered or logged-in, and are browsing as an Unregistered User.
  <% end %>
</div>
<div class="login-status-nav">
  <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, :method =>'delete') %>&nbsp; | &nbsp;
  <% else %>
      <%= link_to('Login', new_user_session_path)  %>&nbsp; | &nbsp;
  <% end %>
  <% if user_signed_in? %>
      <%= link_to('Edit account', edit_user_registration_path) %>
    <% if current_user.has_role? :admin %>
      &nbsp; | &nbsp;<%= link_to('Admin', users_path) %>
    <% end %>
  <% else %>
      <%= link_to('Sign Up', new_user_registration_path)  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Epicurio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Epicurio" %>">
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>

  <header class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container-fluid">
        <%= render 'layouts/navigation_main' %>
        <%= render 'layouts/navigation_user' %>
      </div>
    </nav>
  </header>
  <div id="main" role="main" class="wrapper">
    <div class="container">
      <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>

          <%= yield %>

        </div>
      </div>
    </div>
    <!--<footer>-->
    <!--</footer>-->
    <div class="push"></div>
  </div>

  <div class="footer">
    v 1.0.1
  </div>

  </body>

  <script type="text/javascript">
    /* Disqus JS include trickiness ... reviewec by: BDE */
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'epicurio'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  </script>

</html>